# Generated by Django 4.2.30 on 2026-05-01 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Acteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                ("prenom", models.CharField(max_length=100, verbose_name="Prénom")),
                (
                    "mensurations",
                    models.TextField(blank=True, verbose_name="Mensurations"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Compte utilisateur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acteur",
                "verbose_name_plural": "Acteurs",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Costume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "couleur",
                    models.CharField(
                        choices=[
                            ("rouge", "Rouge"),
                            ("bleu", "Bleu"),
                            ("vert", "Vert"),
                            ("noir", "Noir"),
                            ("blanc", "Blanc"),
                            ("or", "Or"),
                            ("violet", "Violet"),
                            ("bordeaux", "Bordeaux"),
                            ("rose", "Rose"),
                            ("gris", "Gris"),
                            ("marron", "Marron"),
                            ("orange", "Orange"),
                        ],
                        max_length=20,
                        verbose_name="Couleur",
                    ),
                ),
                (
                    "taille",
                    models.CharField(
                        choices=[
                            ("xs", "XS"),
                            ("s", "S"),
                            ("m", "M"),
                            ("l", "L"),
                            ("xl", "XL"),
                            ("xxl", "XXL"),
                        ],
                        default="m",
                        max_length=5,
                        verbose_name="Taille",
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("neuf", "Neuf"),
                            ("bon", "Bon état"),
                            ("reparer", "À réparer"),
                            ("use", "Usé"),
                        ],
                        default="bon",
                        max_length=10,
                        verbose_name="État",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "date_emprunt",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'emprunt"
                    ),
                ),
                (
                    "date_ajout",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'ajout"
                    ),
                ),
                (
                    "acteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costumes_empruntes",
                        to="costumes.acteur",
                        verbose_name="Acteur emprunteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Costume",
                "verbose_name_plural": "Costumes",
                "ordering": ["type_costume__libelle"],
            },
        ),
        migrations.CreateModel(
            name="TypeCostume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "epoque",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Époque / Style"
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de costume",
                "verbose_name_plural": "Types de costumes",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueEmprunt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("emprunt", "Emprunt"),
                            ("retour", "Retour"),
                            ("reset", "Réinitialisation admin"),
                        ],
                        max_length=10,
                        verbose_name="Action",
                    ),
                ),
                ("date_action", models.DateField(verbose_name="Date de l'action")),
                ("note", models.TextField(blank=True, verbose_name="Note")),
                (
                    "acteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="costumes.acteur",
                        verbose_name="Acteur",
                    ),
                ),
                (
                    "costume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="costumes.costume",
                        verbose_name="Costume",
                    ),
                ),
                (
                    "enregistre_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enregistré par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique d'emprunt",
                "verbose_name_plural": "Historiques d'emprunts",
                "ordering": ["-date_action", "-id"],
            },
        ),
        migrations.AddField(
            model_name="costume",
            name="type_costume",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="costumes.typecostume",
                verbose_name="Type de costume",
            ),
        ),
    ]
